### ISSUE TITLE
update requirement.sh

### ISSUE THREAD

**Issue by lotusxai** [lotusxai/pet-days#12]
R package installment does not check for existing packages. needs to be done in R environment. create a list from the librariest (c) from everyline in the requi.txt and create a function that checks for library first.
OR
use condaR. check conda r from conda project.

**Comment by NadiaAntony** [comment]
I could create an Rscript to run this check, and do the installs instead of using bash file run_requirements.sh. The code would then also setup db and run the app (do all in 1 script #13 ). eg:
```
# e.g - setupandrun_app.R 

# installs packages only if not present  
install_checkedpkg <- function(pkg) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
        install.packages(pkg, repos = "https://cloud.r-project.org/")
    }
}

install_checkedpkg("shiny") #1 example

#set up the sqlite db
source("setup_db.R")

# run the shiny app
shiny::runApp(launch.browser = TRUE)
```
depending on comment #14 i'll update the install.packages() command
